Repository viamrobotics/rdk, pull requests merged in 2023-04, with the labels that each got.

#2115 RSDK-2183 - WebRTC track names should be to spec
  resource/resource.go
  robot/web/web.go
Labels: safe to test

#2142 RSDK-2521 Add ConvertedAttributes to module configs
  examples/customresources/models/mybase/mybase.go
  module/module.go
Labels: safe to test

#2108 RSDK-1899 rearchitect backend of constraint system in anticipation of new constraints being added
  motionplan/cBiRRT.go
  motionplan/cBiRRT_test.go
  motionplan/combinedInverseKinematics.go
  motionplan/constraint.go
  motionplan/constraint_test.go
  motionplan/dubinsRRT.go
  motionplan/dubinsRRT_test.go
  motionplan/inverseKinematics.go
  motionplan/kinematic_test.go
  motionplan/metrics.go
  motionplan/metrics_test.go
  motionplan/motionPlanner.go
  motionplan/motionPlanner_test.go
  motionplan/nearestNeighbor.go
  motionplan/nloptInverseKinematics.go
  motionplan/planManager.go
  motionplan/plannerOptions.go
  motionplan/rrt.go
  motionplan/rrtStarConnect.go
  motionplan/utils.go
  referenceframe/primitives.go
  services/motion/builtin/builtin_test.go
Labels: safe to test

#2114 RSDK-2389 Support reconfiguration of modules
  config/data/diff_config_1.json
  config/data/diff_config_2.json
  config/diff.go
  config/diff_test.go
  module/modmanager/data/simplemoduleruncopy.sh
  module/modmanager/manager.go
  module/modmanager/manager_test.go
  module/modmaninterface/interface.go
  module/module.go
  robot/impl/local_robot.go
  robot/impl/local_robot_test.go
Labels: safe to test

#2156 disable selecting text on wasd buttons
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/keyboard-input.vue
Labels: safe to test

#2150 RSDK-2435 Remove Dev Flag RDK
  services/slam/builtin/builtin.go
  services/slam/slam_copy/config/config.go
  services/slam/slam_copy/config/config_test.go
Labels: safe to test

#2153 RSDK-2401 move to position calls with particular start goal specifications will erroneously fail
  motionplan/cBiRRT.go
Labels: safe to test

#2157 Add support for nanopi boards supported by periph.io
  components/board/nanopi/board.go
  components/board/register/register.go
Labels: safe to test

#2163 Bump periph versions
  go.mod
  go.sum
Labels: safe to test

#2158 RSDK-2562 Use native jpeg decoding for ffmpeg until we understand why libjpeg doesn't work
  components/camera/ffmpeg/ffmpeg.go
Labels: safe to test

#2164 RSDK-2563 add MoveOnMap to motion service
  go.mod
  go.sum
  robot/impl/resource_manager_test.go
  services/motion/builtin/builtin.go
  services/motion/builtin/builtin_test.go
  services/motion/client.go
  services/motion/client_test.go
  services/motion/motion.go
  services/motion/motion_test.go
  services/motion/server.go
  services/motion/server_test.go
  testutils/inject/motion_service.go
Labels: safe to test

#2166 [RSDK-2552] Remove WorldState from affected components
  components/arm/arm.go
  components/arm/arm_test.go
  components/arm/client.go
  components/arm/client_test.go
  components/arm/eva/eva.go
  components/arm/fake/fake.go
  components/arm/server.go
  components/arm/server_test.go
  components/arm/universalrobots/ur.go
  components/arm/universalrobots/ur5e_test.go
  components/arm/wrapper/wrapper.go
  components/arm/xarm/xarm_comm.go
  components/arm/yahboom/dofbot.go
  components/gantry/client.go
  components/gantry/client_test.go
  components/gantry/fake/gantry.go
  components/gantry/gantry.go
  components/gantry/multiaxis/multiaxis.go
  components/gantry/multiaxis/multiaxis_test.go
  components/gantry/oneaxis/oneaxis.go
  components/gantry/oneaxis/oneaxis_test.go
  components/gantry/server.go
  components/gantry/server_test.go
  go.mod
  go.sum
  robot/client/client_test.go
  robot/impl/local_robot_test.go
  services/motion/builtin/builtin.go
  testutils/inject/arm.go
  testutils/inject/gantry.go
Labels: safe to test

#2176 Prevent int overflows on 32-bit
  components/sensor/power_ina219/power_ina219.go
Labels: safe to test

#2155 Upgrade client dependencies
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/arm.vue
  web/frontend/src/components/base.vue
  web/frontend/src/components/camera/camera-manager.ts
  web/frontend/src/components/do-command.vue
  web/frontend/src/components/gantry.vue
  web/frontend/src/components/keyboard-input.vue
  web/frontend/src/components/motor-detail.vue
  web/frontend/src/components/movement-sensor.vue
  web/frontend/src/components/operations-sessions.vue
  web/frontend/src/components/pcd/pcd-view.vue
  web/frontend/src/components/remote-control-cards.vue
  web/frontend/src/components/servo.vue
  web/frontend/src/components/slam-2d-render.vue
  web/frontend/src/components/slam.vue
  web/frontend/src/global.d.ts
  web/frontend/src/vite-env.d.ts
  web/frontend/tsconfig.json
Labels: safe to test

#2174 RSDK 2578: Add ML Model Service to RDK
  services/mlmodel/client.go
  services/mlmodel/client_test.go
  services/mlmodel/mlmodel.go
  services/mlmodel/mlmodel_test.go
  services/mlmodel/register/register.go
  services/mlmodel/server.go
  services/mlmodel/server_test.go
  services/register/all.go
Labels: safe to test

#2168 RSDK-2526 unable to move multiaxis gantry
  components/gantry/multiaxis/multiaxis.go
  components/gantry/multiaxis/multiaxis_test.go
  components/gantry/oneaxis/oneaxis.go
Labels: safe to test

#2167 Rsdk-2525 stepper motors speed increases result in unintuitive behavior
  components/motor/gpiostepper/gpiostepper.go
  components/motor/gpiostepper/gpiostepper_test.go
Labels: safe to test

#2180 [RSDK-2631] Allow GPIO pins on genericlinux boards to act as inputs again! :scream:
  components/board/genericlinux/gpio.go
Labels: safe to test

#2184 RSDK-2010 Part I Skip TestEulerAnglesConversion test on arm64
  spatialmath/quat_test.go
Labels: safe to test

#2170 RSDK-2393 Remove name parameter from SLAM interface functions
  components/base/wheeled/kinematics.go
  services/slam/builtin/builtin.go
  services/slam/builtin/builtin_test.go
  services/slam/builtin/cartographer_int_test.go
  services/slam/builtin/orbslam_int_test.go
  services/slam/client.go
  services/slam/client_test.go
  services/slam/fake/slam.go
  services/slam/fake/slam_test.go
  services/slam/server.go
  services/slam/server_test.go
  services/slam/slam.go
  testutils/inject/slam_service.go
Labels: safe to test

#2178 RSDK-2380 Check if labels file is split by spaces or commas
  .artifact/tree.json
  services/vision/builtin/tflite_classifier.go
  services/vision/builtin/tflite_detector.go
  services/vision/builtin/tflite_test.go
Labels: safe to test

#2191 Remove stop call on unmounted
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/base.vue
Labels: safe to test

#2188 RSDK-1902 Random panic occurring somewhere in CBiRRT method
  motionplan/cBiRRT.go
  motionplan/cBiRRT_test.go
  motionplan/nearestNeighbor.go
  motionplan/nearestNeighbor_test.go
Labels: safe to test

#2190 [RSDK-2259, et. al.] Remove RobotConstructor, clean up constraint descriptions
  components/arm/arm.go
  components/arm/arm_test.go
  components/arm/eva/eva.go
  components/arm/fake/fake.go
  components/arm/universalrobots/ur.go
  components/arm/universalrobots/ur5e_test.go
  components/arm/wrapper/wrapper.go
  components/arm/wrapper/wrapper_test.go
  components/arm/xarm/xarm.go
  components/arm/xarm/xarm_comm.go
  components/arm/yahboom/dofbot.go
  examples/simpleserver/cmd.go
  motionplan/constraint.go
  motionplan/constraint_test.go
  motionplan/planManager.go
  motionplan/plannerOptions.go
Labels: safe to test

#2160 [RSDK-1705] add colormap for SLAM UI
  web/frontend/package.json
  web/frontend/src/components/slam-2d-render.vue
Labels: appimage, safe to test

#2162 RSDK-2273 Lock model during Read func
  ml/inference/tflite.go
  services/vision/builtin/tflite_test.go
Labels: safe to test

#2161 RSDK-2478: Update encoder driver methods
  components/board/arduino/encoder.go
  components/board/pi/impl/external_hardware_test.go
  components/encoder/AMS/ams_as5048.go
  components/encoder/AMS/ams_as5048_test.go
  components/encoder/client.go
  components/encoder/client_test.go
  components/encoder/collectors.go
  components/encoder/encoder.go
  components/encoder/encoder_test.go
  components/encoder/errors.go
  components/encoder/fake/encoder.go
  components/encoder/fake/encoder_test.go
  components/encoder/features.go
  components/encoder/incremental/incremental_encoder.go
  components/encoder/incremental/incremental_test.go
  components/encoder/register/register.go
  components/encoder/server.go
  components/encoder/server_test.go
  components/encoder/single/single_encoder.go
  components/encoder/single/single_encoder_test.go
  components/motor/fake/motor.go
  components/motor/gpio/motor_encoder.go
  components/motor/gpio/motor_encoder_test.go
  components/register/all.go
  config/config_test.go
  go.mod
  go.sum
  testutils/inject/encoder.go
Labels: safe to test

#2173 RSDK-2573-fix-text-overlay-sizing
  components/camera/transformpipeline/classifier_test.go
  rimage/draw.go
Labels: safe to test

#2194 NPM 0.2.14 -> 0.2.15
  web/frontend/package.json
Labels: safe to test

#2179 Change default to camera server choosing getImage response Mimetype
  components/camera/client.go
  components/camera/client_test.go
  robot/client/client_test.go
Labels: safe to test

#2199 RSDK-2312 Add new artifact for collision detection
  .artifact/tree.json
Labels: safe to test

#2192 Add a valid arm-model to fake configuration
  etc/configs/fake.json
Labels: safe to test

#2154 DATA-1280 filter out viam_unknown label
  vision/classification/classification_utils.go
Labels: safe to test

#2186 RSDK-2312 build functionality to use maps generated from slam in planning
  motionplan/constraint.go
  pointcloud/basic_octree.go
  pointcloud/basic_octree_test.go
  pointcloud/basic_octree_utils.go
  pointcloud/basic_octree_utils_test.go
Labels: safe to test

#2197 RSDK-2607 add support for xarm lite
  components/arm/fake/fake.go
  components/arm/xarm/xarm.go
  components/arm/xarm/xarmlite_kinematics.json
Labels: safe to test

#2204 ML model API change
  go.mod
  go.sum
  services/mlmodel/client.go
  services/mlmodel/client_test.go
  services/mlmodel/mlmodel.go
  services/mlmodel/mlmodel_test.go
  services/mlmodel/server_test.go
Labels: safe to test

#2202 [RSDK-2332] Get hardware PWM to work on the BeagleBone
  components/board/beaglebone/data.go
  components/board/genericlinux/data.go
  components/board/genericlinux/hw_pwm.go
Labels: safe to test

#2205 create mlmodel_service in testutils/inject
  testutils/inject/mlmodel_service.go
Labels: safe to test

#2210 [DATA-928] Fetch tabular data in CLI via multiple requests
  cli/data.go
Labels: safe to test

#2208 RSDK-2551 Swallow 143 errors when stopping modules for now
  module/modmanager/manager.go
Labels: safe to test

#2213 RSDK-fix Fix scoping issue in xarm registration
  components/arm/xarm/xarm.go
Labels: safe to test

#2195 Add Stadia gamepad mapping
  components/input/gamepad/gamepad_linux.go
  components/input/gamepad/gamepad_mappings_linux.go
Labels: safe to test

#2187 RSDK-2632 Call addConvertedAttributes from Module.ReconfigureResource
  module/module.go
  module/module_test.go
  testutils/inject/shell_service.go
Labels: safe to test

#2212 [DATA-fix] Use path flag for destination dir.
  cli/viam/main.go
Labels: safe to test

#2185 RSDK-2579 - Create tflite_cpu model for MLMS
  .artifact/tree.json
  rimage/image_file.go
  services/mlmodel/client.go
  services/mlmodel/client_test.go
  services/mlmodel/mlmodel.go
  services/mlmodel/register/register.go
  services/mlmodel/server.go
  services/mlmodel/tflitecpu/tflite_cpu.go
  services/mlmodel/tflitecpu/tflite_cpu_test.go
  services/vision/builtin/tflite_detector.go
Labels: safe to test

#2215 RSDK-2723 Remove Arduino and Viam Gripper
  components/board/arduino/.gitignore
  components/board/arduino/Makefile
  components/board/arduino/board.go
  components/board/arduino/board_test.go
  components/board/arduino/encoder.go
  components/board/arduino/motor.go
  components/board/arduino/motor_test.go
  components/board/arduino/vafw/buffer.cpp
  components/board/arduino/vafw/buffer.h
  components/board/arduino/vafw/encoder.cpp
  components/board/arduino/vafw/encoder.h
  components/board/arduino/vafw/general.h
  components/board/arduino/vafw/motor.cpp
  components/board/arduino/vafw/motor.h
  components/board/arduino/vafw/pwm.cpp
  components/board/arduino/vafw/pwm.h
  components/board/arduino/vafw/vafw.ino
  components/board/arduino/vafw_cpptest/encoder.cpp
  components/board/fake/board.go
  components/board/register/register.go
  components/gripper/register/register.go
  components/gripper/vgripper/v1/v1.go
  components/gripper/vgripper/v1/vgripper_model.json
Labels: safe to test

#2203 RSDK-2639 - Improve fake model for bases
  components/arm/eva/eva.go
  components/arm/fake/fake.go
  components/arm/universalrobots/ur.go
  components/base/base.go
  components/base/fake/base.go
  components/base/fake/fake.go
  components/base/fake/fake_test.go
  components/base/wheeled/kinematics.go
  components/base/wheeled/kinematics_test.go
  components/base/wheeled/wheeled_base.go
Labels: safe to test

#2206 RSDK-2172 Add Injectable SLAM Client (EDIT: Exposed HelperFunction used by viamcartographer]
  services/slam/slam.go
Labels: safe to test

#2219 RSDK-2385 Expose video device name
  components/camera/videosource/webcam.go
  go.mod
  go.sum
Labels: safe to test

#2207 [RSDK-2345] Create digital interrupts if not mentioned in the config
  components/board/genericlinux/board.go
Labels: safe to test

#2221 RSDK-2637: minor roboclaw fixes
  components/motor/roboclaw/roboclaw.go
Labels: appimage, safe to test

#2233 [RSDK-2662] refer to digital interrupts by their names
  components/board/genericlinux/gpio.go
Labels: safe to test

#2242 Remove dynamic tag to use default opus
  Makefile
Labels: safe to test

#2243 Bug fix border color
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/arm.vue
  web/frontend/src/components/audio-input.vue
  web/frontend/src/components/base.vue
  web/frontend/src/components/board.vue
  web/frontend/src/components/camera/cameras-list.vue
  web/frontend/src/components/do-command.vue
  web/frontend/src/components/gamepad.vue
  web/frontend/src/components/gantry.vue
  web/frontend/src/components/gripper.vue
  web/frontend/src/components/input-controller.vue
  web/frontend/src/components/motor-detail.vue
  web/frontend/src/components/movement-sensor.vue
  web/frontend/src/components/navigation.vue
  web/frontend/src/components/operations-sessions.vue
  web/frontend/src/components/pcd/pcd-view.vue
  web/frontend/src/components/sensors.vue
  web/frontend/src/components/servo.vue
  web/frontend/src/components/slam-2d-render.vue
  web/frontend/src/components/slam.vue
  web/frontend/tailwind.config.cjs
Labels: safe to test

#2236 Cleanup of incremental encoder
  components/encoder/incremental/incremental_encoder.go
Labels: safe to test

#2239 Fix a bug, change vision.tflite_cpu to mlmodel.tflite_cpu
  services/mlmodel/tflitecpu/tflite_cpu.go
Labels: safe to test

#2246 RSDK-2356: base.Spin changes speed for different distances
  components/base/wheeled/wheeled_base.go
  components/base/wheeled/wheeled_base_test.go
Labels: safe to test

#2244 [RSDK-2388] [RSDK-2392] Fix timing issues in remote server and module tests
  examples/customresources/demos/remoteserver/server_test.go
  module/module_interceptors_test.go
Labels: safe to test

#2235 RSDK-1979 use new motion service wrapper
  web/frontend/.eslintrc.cjs
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/arm.vue
  web/frontend/src/components/do-command.vue
  web/frontend/src/components/movement-sensor.vue
  web/frontend/src/components/navigation.vue
  web/frontend/src/components/pcd/pcd-view.vue
  web/frontend/src/components/remote-control-cards.vue
  web/frontend/src/components/sensors.vue
  web/frontend/src/components/servo.vue
  web/frontend/src/components/slam.vue
Labels: safe to test

#2227 RSDK 1020 Part I - refactor base, encoded motor struct and tests.
  components/base/base_test.go
  components/base/server.go
  components/motor/gpio/motor_encoder.go
  components/motor/gpio/motor_encoder_test.go
  components/motor/gpio/setup.go
  components/motor/gpiostepper/gpiostepper.go
  components/motor/server.go
Labels: safe to test, appimage-ignore-tests

#2245 RSDK-1170 point to pion/mediadevices commit with huffman table error fix
  go.mod
  go.sum
Labels: safe to test

#2247 RSDK-2613 fix: flaky test
  components/encoder/AMS/ams_as5048_test.go
Labels: safe to test

#2248 RSDK-1020 Part IA change back encoder test pointer change for now, keep skips
  components/motor/gpio/motor_encoder_test.go
Labels: safe to test

#2253 move session expireLoop to 10ms
  config/config.go
  config/config_test.go
  robot/session_manager.go
  session/doc.go
Labels: safe to test

#2250 RSDK-2797 - Allow more than 2 args to modules
  module/module.go
Labels: safe to test

#2249 RSDK-2689 resolve package strings in tflite cpu config to model locations on robot
  robot/impl/local_robot_test.go
  services/mlmodel/tflitecpu/tflite_cpu.go
  services/mlmodel/tflitecpu/tflite_cpu_test.go
Labels: safe to test

#2251 RSDK-2482: add rc card for encoder
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/encoder.vue
  web/frontend/src/components/remote-control-cards.vue
Labels: safe to test

#2256 Remove upx from appimages
  etc/packaging/appimages/viam-server-aarch64.yml
  etc/packaging/appimages/viam-server-x86_64.yml
  packaging.make
Labels: safe to test, appimage-ignore-tests

#2261 Add h-[400px] to safe list
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/tailwind.config.cjs
Labels: safe to test

#2258 RSDK-2692 - Add collectors for MovementSensor LinearAcceleration and Orientation
  components/movementsensor/movementsensor.go
Labels: safe to test

#2266 Fix antique-cache docker build
  etc/Dockerfile.antique-cache
Labels: safe to test

#2267 adjust grpc keepalive
  go.mod
  go.sum
Labels: safe to test

#2264 RSDK-2029 - Remove slam integration tests
  .github/workflows/main.yml
  .github/workflows/pullrequest-trusted.yml
  .github/workflows/slam-integration-test.yml
Labels: safe to test

#2263 Rename PWM -> PWM Duty Cycle
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/board.vue
Labels: safe to test, static-build

#2271 RSDK-2029 - Delete builtin & co
  Makefile
  go.mod
  services/slam/builtin/builtin.go
  services/slam/builtin/builtin_test.go
  services/slam/builtin/cartographer_int_test.go
  services/slam/builtin/orbslam_int_test.go
  services/slam/builtin/orbslam_yaml.go
  services/slam/builtin/orbslam_yaml_test.go
  services/slam/internal/testhelper/testhelper.go
  services/slam/register/register.go
  services/slam/slam_copy/config/config.go
  services/slam/slam_copy/config/config_test.go
  services/slam/slam_copy/config/setup.go
  services/slam/slam_copy/config/setup_test.go
  services/slam/slam_copy/dataprocess/dataprocess.go
  services/slam/slam_copy/dataprocess/dataprocess_test.go
  services/slam/slam_copy/testhelper/testhelper.go
  services/slam/slam_copy/utils/utils.go
  services/slam/slam_copy/utils/utils_test.go
  services/slam/slam_libraries.go
Labels: safe to test

#2273 Make TS SDK a peer dependency
  web/frontend/README.md
  web/frontend/package-lock.json
  web/frontend/package.json
Labels: safe to test

#2268 Disconnect before browser tab unload
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/remote-control-cards.vue
  web/frontend/src/lib/resource.ts
Labels: safe to test

#2274 remove comment about digital interrupt callbacks
  components/board/digital_interrupts.go
Labels: safe to test

#2276 Find cameras connected to computer after server start
  components/camera/videosource/webcam.go
  go.mod
  go.sum
Labels: safe to test

#2275 Rsdk-2806: Movement sensor distance to meters
  components/movementsensor/adxl345/adxl345.go
  components/movementsensor/client.go
  components/movementsensor/gpsnmea/nmeaParser.go
  components/movementsensor/gpsnmea/nmeaParser_test.go
  components/movementsensor/movementsensor.go
  components/movementsensor/mpu6050/mpu6050.go
  components/movementsensor/mpu6050/mpu6050_test.go
  components/movementsensor/server.go
  components/movementsensor/server_test.go
  go.mod
  go.sum
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/movement-sensor.vue
Labels: safe to test

#2278 nit: switch to bool
  components/camera/videosource/webcam.go
Labels: safe to test

#2254 RSDK-2224 New vision service
  .artifact/tree.json
  components/camera/transformpipeline/classifier.go
  components/camera/transformpipeline/classifier_test.go
  components/camera/transformpipeline/detector.go
  components/camera/transformpipeline/detector_test.go
  go.mod
  go.sum
  robot/impl/local_robot_test.go
  robot/impl/resource_manager_test.go
  robot/impl/robot_reconfigure_test.go
  services/mlmodel/mlmodel.go
  services/mlmodel/tflitecpu/tflite_cpu.go
  services/mlmodel/tflitecpu/tflite_cpu_test.go
  services/mlmodel/verify_main_test.go
  services/vision/builtin/builtin.go
  services/vision/builtin/builtin_notsupported.go
  services/vision/builtin/builtin_test.go
  services/vision/builtin/color_registration_test.go
  services/vision/builtin/helpers_test.go
  services/vision/builtin/object_detection_test.go
  services/vision/builtin/object_segmentation_test.go
  services/vision/builtin/registration.go
  services/vision/builtin/registry.go
  services/vision/builtin/registry_test.go
  services/vision/builtin/tflite_classifier.go
  services/vision/builtin/tflite_detector.go
  services/vision/builtin/tflite_test.go
  services/vision/client.go
  services/vision/client_test.go
  services/vision/colordetector/color_detector.go
  services/vision/colordetector/color_detector_test.go
  services/vision/data/empty.json
  services/vision/data/fake.json
  services/vision/detectionstosegments/detections_to_3dsegments.go
  services/vision/detectionstosegments/detections_to_3dsegments_test.go
  services/vision/helpers_test.go
  services/vision/mlvision/classifier.go
  services/vision/mlvision/detector.go
  services/vision/mlvision/ml_model.go
  services/vision/mlvision/ml_model_test.go
  services/vision/mlvision/segmenter3d.go
  services/vision/radiusclustering/radius_clustering.go
  services/vision/radiusclustering/radius_clustering_test.go
  services/vision/register/register.go
  services/vision/server.go
  services/vision/server_test.go
  services/vision/vision.go
  services/vision/vision_test.go
  testutils/inject/vision_service.go
  vision/objectdetection/color_detector.go
  vision/segmentation/detections_to_objects.go
  vision/segmentation/radius_clustering.go
  vision/segmentation/radius_clustering_voxel.go
Labels: safe to test

#2279 Check for self-managed connections
  web/frontend/README.md
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/app.vue
  web/frontend/src/components/remote-control-cards.vue
  web/frontend/src/main-lib.ts
Labels: safe to test

#2280 Fix static release script
  etc/packaging/static/package_release.sh
  packaging.make
Labels: safe to test

#2281 rc: remove external from template
  robot/web/web.go
  web/runtime-shared/templates/webappindex.html
Labels: safe to test

#2285 RSDK-2279 Remove Extra Parentheses in SLAM 3D View
  web/frontend/src/components/slam.vue
Labels: safe to test

#2269 RSDK-2821 Update Frontend SLAM 2D View to XY Plane
  .artifact/tree.json
  components/base/fake/fake.go
  components/base/wheeled/kinematics.go
  components/base/wheeled/kinematics_test.go
  services/slam/fake/data_loader.go
  services/slam/fake/slam.go
  services/slam/fake/slam_test.go
  web/frontend/src/components/slam-2d-render.vue
Labels: safe to test

#2286 Fix unmounting issues with RC UI
  web/frontend/package.json
  web/frontend/src/components/remote-control-cards.vue
  web/frontend/src/lib/resize.ts
  web/frontend/src/main.ts
Labels: safe to test

#2287 RSDK-2877 Do not overload usage of term Orphaned
  robot/impl/local_robot.go
  robot/impl/local_robot_test.go
Labels: safe to test

#2283 [RSDK-2226] audit GPIO servo code
  components/servo/gpio/servo.go
  components/servo/gpio/servo_test.go
Labels: safe to test

#2293 RSDK-2885 Fix race
  spatialmath/box.go
  spatialmath/capsule.go
Labels: safe to test

#2292 RSDK-1053-reenable-staticcheck-linter
  etc/.golangci.yaml
Labels: safe to test

#2294 RSDK-2482 FIX: encoder RC card
  web/frontend/src/components/encoder.vue
Labels: safe to test

#2296 APP-1676 - include pi configs in non pi environment
  components/board/pi/common/config.go
  components/board/pi/pi_notsupported.go
Labels: safe to test

#2282 RSDK-2811 - get classifications on a detector new vision service
  services/vision/mlvision/classifier.go
  services/vision/mlvision/detector.go
  services/vision/mlvision/ml_model.go
  services/vision/mlvision/ml_model_test.go
Labels: safe to test

#2297 remove unused import
  components/board/genericlinux/board.go
Labels: safe to test

#2284 Make RC SDK client self managed
  web/frontend/README.md
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/app.vue
  web/frontend/src/components/base.vue
  web/frontend/src/components/camera/camera.vue
  web/frontend/src/components/camera/cameras-list.vue
  web/frontend/src/components/camera/stream-manager.ts
  web/frontend/src/components/encoder.vue
  web/frontend/src/components/gamepad.vue
  web/frontend/src/components/movement-sensor.vue
  web/frontend/src/components/navigation.vue
  web/frontend/src/components/remote-control-cards.vue
  web/frontend/src/components/slam-2d-render.vue
  web/frontend/src/components/slam.vue
  web/frontend/src/main-lib.ts
Labels: safe to test

#2289 [RSDK-734] Make all tests clean up files, use t.TempDir()
  components/camera/transformpipeline/mods_test.go
  components/camera/videosource/join_pointcloud_test.go
  config/watcher_test.go
  examples/customresources/demos/complexmodule/moduletest/module_test.go
  examples/customresources/demos/remoteserver/server_test.go
  module/module_interceptors_test.go
  pointcloud/pointcloud_file_test.go
  rimage/color_cluster_test.go
  rimage/color_test.go
  rimage/depth_map_test.go
  rimage/gradient_test.go
  rimage/image_processing_test.go
  rimage/test_helper.go
  rimage/transform/camera_matrix_test.go
  rimage/transform/cmd/extrinsic_calibration/main_test.go
  rimage/transform/pinhole_camera_parameters_test.go
  rimage/utils_test.go
  rimage/warp_test.go
  robot/impl/local_robot_test.go
  robot/impl/resource_manager_test.go
  robot/impl/robot_reconfigure_test.go
  robot/web/web_test.go
  vision/chess/chess_util_test.go
  vision/chess/piece_test.go
Labels: safe to test

#2295 RSDK-2482 bump rc version
  web/frontend/package-lock.json
  web/frontend/package.json
Labels: safe to test

#2290 [DATA-1351]: Update CLI tool BE
  cli/viam/main.go
Labels: safe to test

#2255 RSDK-2357: Add warn message when MoveStraight call has set the motor speed too low
  components/base/wheeled/wheeled_base.go
  components/motor/dimensionengineering/sabertooth.go
  components/motor/dimensionengineering/sabertooth_test.go
  components/motor/dmc4000/dmc.go
  components/motor/dmc4000/dmc4000_test.go
  components/motor/fake/motor.go
  components/motor/fake/motor_test.go
  components/motor/gpio/basic.go
  components/motor/gpio/basic_test.go
  components/motor/gpio/motor_encoder.go
  components/motor/gpiostepper/gpiostepper.go
  components/motor/gpiostepper/gpiostepper_test.go
  components/motor/i2cmotors/ezopmp.go
  components/motor/roboclaw/roboclaw.go
  components/motor/tmcstepper/stepper_motor_tmc.go
  components/motor/tmcstepper/stepper_motor_tmc_test.go
  components/motor/ulnstepper/28byj-48.go
  components/motor/ulnstepper/28byj-48_test.go
Labels: safe to test

#2241 Update softrobotics gripper sample.json
  components/gripper/softrobotics/sample.json
Labels: safe to test

#2291 RSDK-2886 Reduce config ticker and simplify completeConfig goroutine
  robot/impl/local_robot.go
  robot/impl/resource_manager.go
  robot/impl/robot_reconfigure_test.go
Labels: safe to test

#2300 rc: set height on google map via id
  web/frontend/package-lock.json
  web/frontend/package.json
  web/frontend/src/components/navigation.vue
  web/frontend/src/index.css
Labels: safe to test

#2288 RSDK-1229 RSDK-2693 Remove robot from motion service constructor, and prepare for removal from framesystem service constructor
  components/arm/xarm/xarm.go
  components/arm/xarm/xarm_comm.go
  components/camera/videosource/join_pointcloud.go
  components/camera/videosource/join_pointcloud_test.go
  motionplan/motionPlanner.go
  robot/framesystem/errors.go
  robot/framesystem/framesystem.go
  robot/framesystem/framesystem_utils.go
  robot/framesystem/service_test.go
  robot/impl/local_robot_test.go
  robot/impl/resource_manager_modular_test.go
  services/motion/builtin/builtin.go
  services/motion/builtin/builtin_test.go
  services/motion/data/fake_tomato.json
Labels: safe to test

#2301 RSDK-2867-Make Classification Labels Visible
  components/camera/transformpipeline/classifier_test.go
  services/mlmodel/tflitecpu/tflite_cpu.go
  services/vision/mlvision/detector.go
  services/vision/mlvision/ml_model.go
  services/vision/mlvision/ml_model_test.go
Labels: safe to test

#2260 RSDK-2489
  web/frontend/src/components/slam.vue
Labels: safe to test

#2298 Refactor genericlinux reconfiguration, in preparation for RSDK-2683
  components/board/digital_interrupts.go
  components/board/genericlinux/board.go
Labels: safe to test

#2302 Grab weak dependencies during reconfigure
  robot/impl/local_robot.go
  robot/impl/robot_reconfigure_test.go
Labels: safe to test

#2303 RSDK-2645 - Fix for wrapper arm status breaking Arm RC cards when out-of-bounds
  components/arm/arm.go
  components/arm/arm_test.go
Labels: safe to test

#2237 RSDK-1761 Jetson Orin Daughterboard Detection
  components/camera/platforms/jetson/README.md
  components/camera/platforms/jetson/camera.go
  components/camera/platforms/jetson/data.go
  components/camera/videosource/webcam.go
Labels: safe to test

#2305 Add resource equality check to DataCaptureConfig.Equals
  components/camera/collectors.go
  services/datamanager/data_manager.go
Labels: safe to test

#2306 RSDK-2545 - Allow mDNS fallthrough
  .github/workflows/npm-publish.yml
  go.mod
  go.sum
Labels: safe to test
