Repository viamrobotics/rdk, pull requests merged in 2023-02, with the labels that each got.

#1824 RSDK-1732 Fix for Flaky Cartographer SLAM Test
  services/slam/builtin/cartographer_int_test.go
Labels: safe to test, viam-org

#1653 [DATA-751] Add RTSP model
  .artifact/tree.json
  components/camera/register/register.go
  components/camera/rtsp/decode.go
  components/camera/rtsp/rtsp.go
  components/camera/rtsp/rtsp_test.go
  components/camera/rtsp/verify_main_test.go
  go.mod
  go.sum
Labels: safe to test, viam-org

#1831 DATA-751-fix : respect cancellations, never fully block the RTSP model
  components/camera/rtsp/rtsp.go
Labels: safe to test, viam-org

#1810 [RSDK-1008] Add GPIO support for Jetson Orin
  components/board/beaglebone/board.go
  components/board/beaglebone/data.go
  components/board/genericlinux/board.go
  components/board/genericlinux/board_test.go
  components/board/genericlinux/data.go
  components/board/genericlinux/gpio.go
  components/board/genericlinux/gpio_unsupported.go
  components/board/jetson/board.go
  components/board/jetson/data.go
  components/board/pi/common/common.go
  components/board/pi/impl/board.go
  components/board/pi/impl/board_test.go
  components/board/pi/impl/external_hardware_test.go
  components/board/ti/board.go
  components/board/ti/data.go
  go.mod
  go.sum
Labels: safe to test, viam-org

#1829 DATA-885 - Add PackageManager service
  config/config.go
  config/config_test.go
  config/diff.go
  config/reader.go
  go.mod
  go.sum
  robot/client/client.go
  robot/impl/local_robot.go
  robot/impl/local_robot_test.go
  robot/impl/resource_manager_test.go
  robot/packages/cloud_package_manager.go
  robot/packages/cloud_package_manager_test.go
  robot/packages/noop_package_manager.go
  robot/packages/package_manager.go
  robot/packages/testutils/example.tar.gz
  robot/packages/testutils/fake_package_server.go
  robot/packages/verify_main_test.go
  robot/robot.go
  services/datamanager/model/model.go
  testutils/inject/robot.go
  web/server/entrypoint.go
Labels: safe to test, viam-org

#1834 Add GPIO pin definitions for the Jetson Orin NX
  components/board/jetson/data.go
Labels: safe to test, viam-org

#1833 APP-1086 - Remove unneeded check for non-web auth handler
  robot/web/web.go
Labels: safe to test, viam-org

#1822 RSDK-1653 Fix arm behavior when OOB
  components/arm/arm.go
  components/arm/arm_test.go
  components/arm/client_test.go
  components/arm/eva/eva.go
  components/arm/fake/fake.go
  components/arm/trossen/trossen.go
  components/arm/universalrobots/ur.go
  components/arm/wrapper/wrapper.go
  components/arm/xarm/xarm.go
  motionplan/kinematic.go
  motionplan/kinematic_test.go
  referenceframe/frame.go
  referenceframe/frame_test.go
  testutils/inject/arm.go
Labels: safe to test, viam-org

#1837 fix-build-failure-due-to-useless-Errorf
  components/board/genericlinux/gpio_unsupported.go
Labels: safe to test, viam-org

#1840 [DATA-1053] Bump up API for latest package API changes
  go.mod
  go.sum
Labels: safe to test, viam-org

#1841 [DATA-1053] tidy up go.sum after API bump
  go.sum
Labels: safe to test, viam-org

#1839 RSDK-1681, RSDK-1796 Add additional motion planning logging, add reasons why IK fails in cases where it does so
  motionplan/constraint.go
  motionplan/constraint_test.go
  motionplan/errors.go
  motionplan/motionPlanner.go
  motionplan/motionPlanner_test.go
Labels: safe to test, viam-org

#1843 [DATA-1035] Add option to disable directory configuration
  config/config.go
  robot/impl/resource_manager.go
  services/datamanager/builtin/builtin.go
  services/datamanager/builtin/builtin_test.go
  web/server/entrypoint.go
Labels: safe to test, viam-org

#1845 RSDK-1656: Verify UR5 driver connectivity logic
  components/arm/universalrobots/ur.go
  components/arm/universalrobots/ur5e_test.go
Labels: safe to test, viam-org

#1849 Fix capsule collision bug
  spatialmath/capsule.go
  spatialmath/capsule_test.go
Labels: safe to test, viam-org

#1855 RSDK-1755, RSDK-1872 Allow cloud-configured robot to work off-line using cached config
  config/reader.go
  robot/impl/local_robot.go
Labels: safe to test, viam-org

#1852 RSDK-856 Add a default timeout to all inbound gRPC methods
  robot/web/web.go
  robot/web/web_test.go
Labels: safe to test, viam-org

#1860 [RSDK-1881] Initialize the robot member variable when constructing a dofbot arm
  components/arm/yahboom/dofbot.go
Labels: safe to test, viam-org

#1813 RSDK-1730 - check number of channels for microphone driver selection
  components/audioinput/microphone/microphone.go
Labels: safe to test

#1865 Fix PR Labeler Workflow
  .github/workflows/pr-labeler.yml
  .github/workflows/pullrequest-trusted.yml
Labels: safe to test, viam-org

#1844 [RSDK-1256] Add I2C support for genericlinux boards
  components/board/genericlinux/board.go
  components/board/genericlinux/i2c.go
Labels: safe to test, viam-org

#1869 RSDK-1666 remove flaky MergePoints tests for now
  pointcloud/merging_test.go
Labels: safe to test, viam-org

#1870 RSDK-1273 Error return from intelrealserver causes panic in gostream
  components/camera/videosource/helpers.go
  components/camera/videosource/server_test.go
Labels: safe to test, viam-org

#1859 RSDK-1851 Backend implementation for removing Interaction Spaces from WorldState
  components/arm/arm.go
  components/arm/universalrobots/ur.go
  components/arm/universalrobots/ur5e_test.go
  motionplan/collision_test.go
  motionplan/constraint.go
  motionplan/constraint_test.go
  motionplan/dubinsRRT_test.go
  motionplan/motionPlanner_test.go
  referenceframe/worldstate.go
Labels: safe to test

#1856 Add Doftbot OOB Rescue
  components/arm/yahboom/dofbot.go
Labels: safe to test, viam-org

#1815 Extra documentation for accelerometers
  components/movementsensor/adxl345/adxl345.go
  components/movementsensor/mpu6050/mpu6050.go
Labels: safe to test, viam-org

#1853 RSDK-1655 Verify live updating of all arms
  components/arm/xarm/xarm.go
  components/arm/xarm/xarm_test.go
Labels: safe to test, viam-org

#1851 RSDK-1857 add backend support for collision specifications
  motionplan/collision.go
  motionplan/collision_test.go
  motionplan/constraint.go
  motionplan/constraint_test.go
  motionplan/dubinsRRT_test.go
  motionplan/motionPlanner_test.go
  motionplan/planManager.go
Labels: safe to test, viam-org

#1820 RSDK-1265 - initialize trossen serial connection only once between ar…
  components/arm/trossen/trossen.go
  components/gripper/trossen/bad_config.json
  components/gripper/trossen/good_config.json
  components/gripper/trossen/trossen.go
  components/gripper/trossen/trossen_test.go
Labels: safe to test, viam-org

#1854 Clean up board.I2CHandle interface
  components/arm/yahboom/dofbot.go
  components/board/board_test.go
  components/board/fake/board.go
  components/board/genericlinux/i2c.go
  components/board/i2c.go
  components/board/pi/impl/i2c.go
  components/sensor/bme280/bme280.go
Labels: safe to test, viam-org

#1873 Bump api.
  go.mod
  go.sum
Labels: safe to test, viam-org

#1878 add header field to auto-generated pr comments
  .github/workflows/code-coverage-comment.yml
  .github/workflows/motion-benchmarks-comment.yml
Labels: safe to test, viam-org

#1868 RSDK-888 Stop bases and arms on controller connect events
  services/armremotecontrol/builtin/builtin.go
  services/armremotecontrol/builtin/builtin_ext_test.go
  services/baseremotecontrol/builtin/builtin.go
  services/baseremotecontrol/builtin/builtin_ext_test.go
Labels: safe to test, viam-org

#1880 RSDK-1875 Ensure parent resources are updated when fetched from module
  module/module.go
  module/module_test.go
Labels: safe to test, viam-org

#1863 RSDK-1808: Create classifications transform
  .artifact/tree.json
  components/camera/transformpipeline/classifier.go
  components/camera/transformpipeline/classifier_test.go
  components/camera/transformpipeline/detector.go
  components/camera/transformpipeline/transform.go
  vision/classification/classification_utils.go
  vision/classification/postprocessor.go
Labels: safe to test, viam-org

#1884 RSDK-1935 emptying the config
  config/reader.go
Labels: safe to test, viam-org

#1862 RSDK-1810: implicit dependencies
  components/board/pi/common/common.go
Labels: safe to test, viam-org

#1882 RSDK-1864 changed validation errors from debug to error
  config/config.go
Labels: safe to test, viam-org

#1871 RSDK-1840: Investigate code cleanup on Fake arm component kinematic model and required fields
  components/arm/fake/fake.go
  components/arm/wrapper/wrapper.go
  etc/configs/fake_local_auth.json
  referenceframe/model.go
  referenceframe/transformable.go
  robot/impl/data/diff_config_1.json
  robot/impl/data/diff_config_3_bad.json
  robot/impl/data/diff_config_4_bad.json
  robot/impl/data/diff_config_deps1.json
  robot/impl/data/diff_config_deps10.json
  robot/impl/data/diff_config_deps11.json
  robot/impl/data/diff_config_deps2.json
  robot/impl/data/diff_config_deps3.json
  robot/impl/data/diff_config_deps5.json
  robot/impl/data/diff_config_deps6.json
  robot/impl/data/diff_config_deps9_good.json
  robot/impl/data/fake.json
  robot/impl/data/fake_wrongconfig1.json
  robot/impl/data/fake_wrongconfig2.json
  robot/impl/data/fake_wrongconfig3.json
  robot/impl/data/fake_wrongconfig4.json
  robot/impl/data/frame1.json
  robot/impl/data/remote_fake.json
  robot/impl/local_robot_test.go
  robot/impl/robot_reconfigure_test.go
  services/motion/data/arm_gantry.json
  web/frontend/cypress/data/test_robot_config.json
Labels: safe to test, viam-org

#1883 RSDK-1958 - webcam: fix double close and invalid reuse
  components/audioinput/audio_input.go
  components/audioinput/microphone/microphone.go
  components/camera/camera.go
  components/camera/videosource/camera_waitgroup.go
  components/camera/videosource/webcam.go
  rimage/cmd/stream_camera/main.go
Labels: safe to test, viam-org

#1848 [RSDK-571] Movement sensors: don't report the same error twice
  components/movementsensor/adxl345/adxl345.go
  components/movementsensor/cameramono/cameramono.go
  components/movementsensor/gpsnmea/pmtkI2C.go
  components/movementsensor/gpsnmea/serial.go
  components/movementsensor/gpsrtk/gpsrtk.go
  components/movementsensor/gpsrtk/i2c.go
  components/movementsensor/gpsrtk/ntrip.go
  components/movementsensor/gpsrtk/rtk_station.go
  components/movementsensor/gpsrtk/serial.go
  components/movementsensor/imuwit/imu.go
  components/movementsensor/mpu6050/mpu6050.go
  components/movementsensor/utils.go
  components/movementsensor/utils_test.go
Labels: safe to test, viam-org

#1835 Bee ring implementation needs
  components/sensor/collector.go
  components/sensor/register/register.go
  components/sensor/sensor.go
  components/sensor/sht3xd/sht3xd.go
Labels: safe to test, viam-org

#1838 RSDK-904: 28BYJ-48 stepper implementation
  components/motor/register/register.go
  components/motor/ulnstepper/28byj-48.go
  components/motor/ulnstepper/28byj-48_test.go
Labels: safe to test, appimage-ignore-tests, viam-org

#1866 Code samples
  examples/apis.json
Labels: safe to test, viam-org

#1836 [RSDK-1678] add fake slam
  .artifact/tree.json
  etc/configs/fake.json
  services/slam/fake/slam.go
  services/slam/fake/slam_test.go
  services/slam/register/register.go
Labels: safe to test, viam-org

#1886 RSDK-1900 - fix i2c bus handling in AM5 AS5048 encoder
  components/encoder/am5_as5048.go
Labels: safe to test, viam-org

#1899 update nlopt to support pkg-config builds on mac/linux
  go.mod
  go.sum
Labels: safe to test, viam-org

#1864 Publish RC components to NPM
  .github/workflows/main.yml
  .github/workflows/npm-publish.yml
  web/frontend/package.json
Labels: safe to test, viam-org

#1898 RSDK-2034 - Do not Fatal log module serve error
  module/module.go
Labels: safe to test, viam-org

#1901 Update package.json to use latest version
  web/frontend/package.json
Labels: safe to test, viam-org

#1902 update fake.json for fake arm
  etc/configs/fake.json
  referenceframe/model.go
Labels: safe to test, viam-org

#1857 RSDK-1682 - refactor digital interrupts to pass on machine timestamp …
  components/board/board.go
  components/board/board_test.go
  components/board/client.go
  components/board/digital_interrupts.go
  components/board/digital_interrupts_test.go
  components/board/pi/impl/board.go
  components/encoder/incremental_encoder.go
  components/encoder/single_encoder.go
  components/input/gpio/gpio.go
  components/sensor/ultrasonic/ultrasonic.go
  testutils/inject/digital_interrupt.go
Labels: safe to test, viam-org

#1888 RSDK-1883 - return default orientation vector over nil for movementsensors
  components/movementsensor/adxl345/adxl345.go
  components/movementsensor/gpsnmea/serial.go
  components/movementsensor/movementsensor.go
  components/movementsensor/movementsensor_test.go
  components/movementsensor/mpu6050/mpu6050.go
Labels: safe to test, viam-org

#1910 allow empty fake arm cfg to populate with default
  components/arm/fake/fake.go
  etc/configs/fake.json
Labels: safe to test, viam-org

#1893 RSDK-1944 Add DoCommand to all components
  components/arm/client.go
  components/arm/server.go
  components/audioinput/client.go
  components/audioinput/server.go
  components/base/client.go
  components/base/server.go
  components/board/client.go
  components/board/server.go
  components/camera/client.go
  components/camera/server.go
  components/gantry/client.go
  components/gantry/server.go
  components/gripper/client.go
  components/gripper/server.go
  components/input/client.go
  components/input/server.go
  components/motor/client.go
  components/motor/server.go
  components/movementsensor/client.go
  components/movementsensor/server.go
  components/posetracker/client.go
  components/posetracker/server.go
  components/sensor/client.go
  components/sensor/server.go
  components/servo/client.go
  components/servo/server.go
  etc/.golangci.yaml
  go.mod
  go.sum
  protoutils/messages.go
  resource/resource.go
  robot/impl/local_robot_test.go
Labels: safe to test, viam-org

#1909 RSDK-1967 Genericize FromRobot
  components/arm/arm.go
  components/audioinput/audio_input.go
  components/base/base.go
  components/board/board.go
  components/camera/camera.go
  components/encoder/encoder.go
  components/gantry/gantry.go
  components/generic/generic.go
  components/gripper/gripper.go
  components/input/input.go
  components/motor/motor.go
  components/movementsensor/movementsensor.go
  components/posetracker/pose_tracker.go
  components/sensor/sensor.go
  components/servo/servo.go
  examples/customresources/apis/summationapi/summationapi.go
  robot/robot.go
  robot/robot_test.go
  services/motion/motion.go
  services/navigation/navigation.go
  services/sensors/sensors.go
  services/vision/vision.go
Labels: safe to test, viam-org

#1894 RSDK-1764 - add maxRotation angle to the servo config
  components/board/pi/common/common.go
  components/board/pi/impl/board_test.go
  components/board/pi/impl/servo.go
Labels: safe to test, viam-org

#1914 [RSDK-1609] Fix module test timeouts
  examples/customresources/demos/complexmodule/module_test.go
  module/modmanager/manager.go
  module/modmanager/manager_test.go
Labels: safe to test, viam-org

#1905 [DATA-1089] Don't error on unexpected EOF when reading datacapture file.
  data/collector_test.go
  services/datamanager/builtin/sync_test.go
  services/datamanager/datacapture/data_capture_buffer_test.go
  services/datamanager/datacapture/data_capture_file.go
  services/datamanager/datacapture/data_capture_file_test.go
  services/datamanager/datasync/sync.go
  services/datamanager/datasync/upload_data_capture_file.go
Labels: safe to test, viam-org

#1913 [RSDK-2002] Move slam config & tests to slam repo
  go.mod
  go.sum
  services/slam/builtin/builtin.go
  services/slam/builtin/builtin_test.go
  services/slam/internal/config/config.go
  services/slam/internal/testhelper/testhelper.go
Labels: safe to test, viam-org

#1921 APP-1322 - Code samples bug fix
  examples/apis.json
Labels: safe to test, viam-org

#1896 [RSDK-2019] Hold onto the file descriptors for GPIO pins
  components/board/genericlinux/board.go
  components/board/genericlinux/gpio.go
Labels: safe to test, viam-org

#1889 RSDK 893 refresh in checkConnection when needed
  robot/client/client.go
  robot/client/client_test.go
Labels: safe to test, viam-org

#1912 RSDK-1945 Add DoCommand to all relevant services
  examples/customresources/models/mynavigation/mynavigation.go
  go.mod
  go.sum
  services/datamanager/builtin/builtin.go
  services/datamanager/client.go
  services/datamanager/client_test.go
  services/datamanager/data_manager.go
  services/datamanager/data_manager_test.go
  services/datamanager/server.go
  services/datamanager/server_test.go
  services/motion/builtin/builtin.go
  services/motion/client.go
  services/motion/client_test.go
  services/motion/motion.go
  services/motion/motion_test.go
  services/motion/server.go
  services/motion/server_test.go
  services/navigation/builtin/builtin.go
  services/navigation/client.go
  services/navigation/client_test.go
  services/navigation/navigation.go
  services/navigation/navigation_test.go
  services/navigation/server.go
  services/navigation/server_test.go
  services/sensors/builtin/builtin.go
  services/sensors/client.go
  services/sensors/client_test.go
  services/sensors/sensors.go
  services/sensors/sensors_test.go
  services/sensors/server.go
  services/sensors/server_test.go
  services/shell/builtin/builtin.go
  services/shell/client.go
  services/shell/client_test.go
  services/shell/server.go
  services/shell/server_test.go
  services/shell/shell.go
  services/shell/shell_test.go
  services/slam/builtin/builtin.go
  services/slam/client.go
  services/slam/client_test.go
  services/slam/server.go
  services/slam/server_test.go
  services/slam/slam.go
  services/slam/slam_test.go
  services/vision/builtin/builtin.go
  services/vision/client.go
  services/vision/client_test.go
  services/vision/reconfigure_test.go
  services/vision/server.go
  services/vision/server_test.go
  services/vision/vision.go
  testutils/inject/datamanager_service.go
  testutils/inject/motion_service.go
  testutils/inject/navigation_service.go
  testutils/inject/sensors.go
  testutils/inject/shell_service.go
  testutils/inject/slam_service.go
  testutils/inject/vision_service.go
Labels: safe to test, viam-org

#1922 update gpio_unsupported.go to match gpio.go
  components/board/genericlinux/gpio_unsupported.go
Labels: safe to test, viam-org

#1904 RSDK-1682 - simplify ultrasonic sensor implementation
  components/sensor/ultrasonic/ultrasonic.go
Labels: appimage, safe to test, viam-org

#1929 fix reference frame dof cap out of bounds
  go.mod
  go.sum
  referenceframe/model.go
  robot/web/web.go
  services/navigation/store.go
Labels: safe to test, viam-org

#1907 RSDK-1934 - map pi servo errors to user readable messages
  components/board/pi/common/errors.go
  components/board/pi/impl/servo.go
Labels: safe to test, viam-org

#1930 RSDK-1909 - return 0,0 if position is called before getting any reading of position
  components/movementsensor/gpsnmea/pmtkI2C.go
  components/movementsensor/gpsrtk/gpsrtk.go
Labels: safe to test, viam-org

#1931 [RSDK-1901] update SLAM service tests to use random grpc ports
  services/slam/builtin/builtin_test.go
  services/slam/builtin/orbslam_yaml_test.go
Labels: safe to test, viam-org

#1927 rsdk-1510 - skip join pointcloud test until improvement can be done
  components/board/genericlinux/gpio_unsupported.go
  components/camera/videosource/join_pointcloud_test.go
Labels: safe to test, viam-org

#1934 RSDK-2082 - Fix hanging if robot start up panics
  robot/impl/local_robot.go
  robot/impl/resource_manager_test.go
  web/server/entrypoint.go
Labels: safe to test, viam-org

#1935 RSDK-2074 - Add guards around unix socket address length
  module/modmanager/manager.go
  module/modmanager/manager_test.go
  module/module.go
  robot/web/web.go
Labels: safe to test, viam-org

#1908 RSDK-1898 refactor collision system
  motionplan/collision.go
  motionplan/collision_test.go
  motionplan/constraint.go
  motionplan/constraint_test.go
  motionplan/dubinsRRT_test.go
  motionplan/motionPlanner_test.go
  motionplan/planManager.go
  motionplan/plannerOptions.go
Labels: safe to test, viam-org

#1937 Bump API to latest version
  go.mod
  go.sum
Labels: safe to test, viam-org

#1940 Update FE to version 34 in NPM
  web/frontend/package.json
Labels: safe to test, viam-org

#1890 [Rsdk-1913] add select case to wit imu to close on cancelled context
  components/movementsensor/imuwit/imu.go
Labels: safe to test, viam-org

#1918 RSDK-1795 Fix motion planning sometimes hanging on linear motion to infeasible goals
  motionplan/cBiRRT.go
  motionplan/planManager.go
  motionplan/utils.go
Labels: safe to test, viam-org

#1939 Fix out-of-range error in connecting to microphone
  components/audioinput/microphone/microphone.go
Labels: safe to test, viam-org

#1942 Change fake encoder update_rate_msec to an omitted empty field
  components/encoder/fake/encoder.go
Labels: safe to test, viam-org

#1946 Refactor base and add logger
  components/base/wheeled/wheeled_base.go
  components/base/wheeled/wheeled_base_test.go
Labels: safe to test, viam-org

#1926 RSDK-1903 - change temperature sensor readings to convention names
  components/sensor/bme280/bme280.go
  components/sensor/ds18b20/ds18b20.go
Labels: safe to test, viam-org
